[build]
  publish = "/"

# Configuração específica para o formulário
[forms.contact]
  success_url = "/thanks.html"

# Redirecionamentos
[[redirects]]
  from = "/thanks"
  to = "/thanks.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 