[build]
  publish = "/"

# Configurações do formulário
[forms]
  # Nome do formulário que corresponde ao atributo name="contact"
  [forms.contact]
    # Define redirecionamento após envio do formulário
    success_url = "/thanks.html"

# Redirecionamentos
[[redirects]]
  from = "/thanks"
  to = "/thanks.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 